language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION compile test:compile test publish-local
scala:
   - 2.10.4
before_script:
  - mkdir $TRAVIS_BUILD_DIR/tmp
  - export SBT_OPTS="-Djava.io.tmpdir=$TRAVIS_BUILD_DIR/tmp"
